---
- name: Install llama
  hosts: all
  become: true
  gather_facts: true
  vars:
    llama_version: "b11200"
    llama_artifact_url: >-
      https://huggingface.co/buckets/ggml-org/install.sh/resolve/b11200/x86_64/linux/cpu/ylkkk/llama-app.zst
    llama_artifact_checksum: "sha256:dd7042165a313532c5fdbc0cc06e3d4dc41874d5a326b9026075cb2522064dc9"
  tasks:
    - name: Include llama
      ansible.builtin.include_role:
        name: llama
