---
- name: Install llama
  hosts: all
  become: true
  gather_facts: true
  vars:
    llama_version: "b10612"
    llama_artifact_url: >-
      https://huggingface.co/buckets/ggml-org/install.sh/resolve/b10612/x86_64/linux/cpu/ylkkk/llama-app.zst
    llama_artifact_checksum: "sha256:27b4152996d088103fee64362da6defa72a0d898f8b6282f921b9641027350e7"
  tasks:
    - name: Include llama
      ansible.builtin.include_role:
        name: llama
