---
galaxy_info:
  author: Robert Wimmer
  description: Install Open WebUI from a pinned PyPI package as a systemd service.
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  role_name: openwebui
  namespace: githubixx
  platforms:
    - name: Ubuntu
      versions:
        - noble
        - resolute
    - name: ArchLinux
  galaxy_tags:
    - ai
    - openwebui
    - ollama
    - web
    - ui

dependencies: []
