---
- name: Setup Archlinux hosts
  hosts: archlinux
  gather_facts: false
  become: true
  tasks:
    - name: Init pacman
      ansible.builtin.raw: |
        pacman-key --init
        pacman-key --populate archlinux
      changed_when: false

    - name: Update pacman cache
      ansible.builtin.raw: |
        pacman -Sy
      changed_when: false

    - name: Install Python for Ansible and uv
      ansible.builtin.raw: |
        pacman -S --noconfirm python uv
      changed_when: false

    - name: Upgrade the whole system
      ansible.builtin.raw: |
        pacman --noconfirm -Su
      changed_when: false

    - name: Reboot for kernel updates
      ansible.builtin.reboot:

- name: Setup Ubuntu hosts
  hosts: ubuntu
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Download uv installer
      ansible.builtin.get_url:
        url: https://astral.sh/uv/install.sh
        dest: /tmp/uv-installer.sh
        owner: root
        group: root
        mode: "0755"

    - name: Install uv
      ansible.builtin.command:
        argv:
          - /tmp/uv-installer.sh
          - --quiet
        creates: /usr/local/bin/uv
      environment:
        UV_UNMANAGED_INSTALL: /usr/local/bin

    - name: Remove uv installer
      ansible.builtin.file:
        path: /tmp/uv-installer.sh
        state: absent
